xcopy.exe ..\..\bundles\typical\ING9187xx\meta.json .\temp\ /y
xcopy.exe ..\..\bundles\typical\ING9187xx\platform.bin .\temp\ /y
xcopy.exe ..\..\bundles\typical\ING9187xx\symdefs.m .\temp\ /y
xcopy.exe ..\CustomerApps\meter_module_rtk\meter_module.bin .\temp\ /y
xcopy.exe ..\CustomerApps\meter_module_rtk\config.bin .\temp\ /y
xcopy.exe ..\CustomerApps\meter_module_rtk\listing\meter_module.map .\temp\ /y
xcopy.exe ..\CustomerApps\dianbiao\ValCase.bin .\temp\ /y
xcopy.exe .\icsdw.exe .\temp\ /y
xcopy.exe .\libgcc_s_dw2-1.dll .\temp\ /y
xcopy.exe .\settings.ini .\temp\ /y